### ISSUE TITLE
Inconsistencia en la generación de las mesh

### ISSUE THREAD

**Issue by rglez** [rglez/DiMap#2]
1. Al escoger los valores de angulos que se van a utilizar, se toma 180 y -180 en consideración cuando esto es un error porque son posiciones equivalentes en una circunferencia y no deben estar repetidos.

2. El resultado del siguiente codigo es inconsistente entre las diferentes mesh que se generan, lo cual es un error:

**mk_mesh2:**
In [20]:[len(meshes[x]) for x in meshes]
Out[20]: [36, 36, 36, 36, 36, 36, 36, 36]

**mk_mesh1:**
In [14]: [len(meshes[x]) for x in meshes]
Out[14]: [7, 7, 7, 7, 49, 49, 49, 49]

**Comment by tomascd123** [comment]
Resolving in the new method proposed.
